[package]
name = "pr-stats"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
itertools = "0.13.0"
octocrab = "0.41.2"
rusqlite = "0.32.1"
serde_json = "1.0.133"
tokio = { version = "1.41.1", features = ["rt-multi-thread", "macros", "time"] }
